from DrissionPage import Chromium, ChromiumOptions

co = ChromiumOptions()
print("返回要控制的浏览器地址，格式为 ip:port，默认为'127.0.0.1:9222':", co.address)
print("浏览器可执行文件的路径:", co.browser_path)
print("返回用户数据文件夹路径:",co.user_data_path)
print("该属性返回临时文件夹路径，可用于保存自动分配的用户文件夹路径:",co.tmp_path)
print("默认下载路径文件路径:", co.download_path)
print("用户配置文件夹名称:", co.user)
print("页面加载策略:", co.load_mode)
print("超时设置:", co.timeouts)
print("连接失败时的重试次数:", co.retry_times)
print("连接失败时的重试间隔:", co.retry_interval)
print("代理设置:", co.proxy)
print("list形式返回浏览器启动参数:", co.arguments)
print("list形式返回要加载的插件路径:", co.extensions)
print("用户首选项配置:", co.preferences)
print("是否使用系统按照的浏览器的用户文件夹:", co.system_user_path)
print("是否仅使用已打开的浏览器:", co.is_existing_only)
print("是否仅使用自动分配端口和用户文件夹路径:", co.is_auto_port)
print("是否以无头模式启动浏览器:", co.is_headless)